<a href="https://colab.research.google.com/github/meetdarbar93/AI-ML-Internship/blob/main/Day2/Day2_NumPy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create 1D, 2D, and 3D NumPy arrays.



In [ ]:
#1d array
import numpy as np

arr = np.array([1,2,3,4,5])
print(f"Original array {arr}")
print(f"Array shape {arr.shape}")
print(f"Array Dimension {arr.ndim}")


Original array [1 2 3 4 5]
Array shape (5,)
Array Dimension 1


In [ ]:
#2d array
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,0]])
print(f"Original array \n{arr}")
print(f"Array shape {arr.shape}")
print(f"Array Dimension {arr.ndim}")

Original array 
[[1 2 3 4 5]
 [6 7 8 9 0]]
Array shape (2, 5)
Array Dimension 2


In [ ]:
#3d
arr = np.array([[[1,2,3,4,5],
                 [1,2,3,4,5],
                [6,7,8,9,0]],

                 [[1,2,3,4,5],
                 [1,2,3,4,5],
                [6,7,8,9,0]]])
print(f"Original array \n{arr}")
print(f"Array shape {arr.shape}")
print(f"Array Dimension {arr.ndim}")

Original array 
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [6 7 8 9 0]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [6 7 8 9 0]]]
Array shape (2, 3, 5)
Array Dimension 3


# Perform addition, subtraction, multiplication, and division between arrays.

In [ ]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(f"arr1 = {arr1}")
print(f"arr2 = {arr2}")
print(f"Addition = {arr1 + arr2}")
print(f"Subtraction = {arr1 - arr2}")
print(f"Multiplication = {arr1 * arr2}")
print(f"Division = {arr1 / arr2}")



arr1 = [10 20 30 40]
arr2 = [1 2 3 4]
Addition = [11 22 33 44]
Subtraction = [ 9 18 27 36]
Multiplication = [ 10  40  90 160]
Division = [10. 10. 10. 10.]


# Find mean, median, and standard deviation of an array.


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(f"Array = {arr}")
print(f"Mean = {np.mean(arr)}")
print(f"Median = {np.median(arr)}")
print(f"Standard Deviation = {np.std(arr)}")
print(f"Sum = {np.sum(arr)}")

Array = [10 20 30 40 50]
Mean = 30.0
Median = 30.0
Standard Deviation = 14.142135623730951
Sum = 150


# Create a DataFrame manually using a dictionary.


In [ ]:
import pandas as pd

data = {
    'Name': ['Meet', 'Vedant', 'Jay', 'Yug'],
    'Age': [20, 21, 19, 22],
    'Course': ['BCA', 'B.Tech', 'BSc', 'BCA']
}

df = pd.DataFrame(data)
print(df)


     Name  Age  Course
0    Meet   20     BCA
1  Vedant   21  B.Tech
2     Jay   19     BSc
3     Yug   22     BCA


# Load CSV

In [ ]:

import kagglehub
from kagglehub import KaggleDatasetAdapter

df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "uciml/iris",
    "Iris.csv"
)

print(df.head())


/tmp/ipython-input-2082602038.py:4: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(


   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None


# Display First 10 rows Shape, columns, and data types

In [ ]:
print("First 10 rows:\n")
print(df.head(10))

print("\nShape of DataFrame:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataFrame Info:")
df.info()


First 10 rows:

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

Shape of DataFrame:
(150, 6)

Column Names:
['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']

DataFra

#Mean, median, and mode of numeric columns


In [ ]:
print("Mean of numeric column:\n")
print(df.mean(numeric_only=True))

print("\nMedian of numeric column:\n")
print(df.median(numeric_only=True))

print("\nMode of numeric columns:\n")
print(df.mode(numeric_only=True).iloc[0])


Mean of numeric column:

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

Median of numeric column:

Id               75.50
SepalLengthCm     5.80
SepalWidthCm      3.00
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64

Mode of numeric columns:

Id               1.0
SepalLengthCm    5.0
SepalWidthCm     3.0
PetalLengthCm    1.5
PetalWidthCm     0.2
Name: 0, dtype: float64


#Filter rows where a numeric column > some value.


In [ ]:
filtered_df = df[df["SepalLengthCm"] > 5]

print("Rows where Sepal Length Cm > 5:\n")
print(filtered_df.head())


Rows where SepalLengthCm > 5:

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa


#Sort the DataFrame by a column in descending order.


In [ ]:
sorted_df = df.sort_values(by="SepalLengthCm", ascending=False)

print("DataFrame sorted by SepalLengthCm in descending order:\n")
print(sorted_df.head(10))


DataFrame sorted by SepalLengthCm in descending order:

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
131  132            7.9           3.8            6.4           2.0   
122  123            7.7           2.8            6.7           2.0   
118  119            7.7           2.6            6.9           2.3   
117  118            7.7           3.8            6.7           2.2   
135  136            7.7           3.0            6.1           2.3   
105  106            7.6           3.0            6.6           2.1   
130  131            7.4           2.8            6.1           1.9   
107  108            7.3           2.9            6.3           1.8   
109  110            7.2           3.6            6.1           2.5   
129  130            7.2           3.0            5.8           1.6   

            Species  
131  Iris-virginica  
122  Iris-virginica  
118  Iris-virginica  
117  Iris-virginica  
135  Iris-virginica  
105  Iris-virginica  
130  Iris-virginica

#Add a new column calculated from existing columns.


In [ ]:
df["SepalArea"] = df["SepalLengthCm"] * df["SepalWidthCm"]

print("First 5 rows with new column:\n")
print(df.head())


First 5 rows with new column:

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa   
1   2            4.9           3.0            1.4           0.2  Iris-setosa   
2   3            4.7           3.2            1.3           0.2  Iris-setosa   
3   4            4.6           3.1            1.5           0.2  Iris-setosa   
4   5            5.0           3.6            1.4           0.2  Iris-setosa   

   SepalArea  
0      17.85  
1      14.70  
2      15.04  
3      14.26  
4      18.00  


# Drop column

In [ ]:
df = df.drop(columns=["Id"])

print("After dropping 'Id' column:\n")
print(df.head())


After dropping 'Id' column:

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0            5.1           3.5            1.4           0.2  Iris-setosa   
1            4.9           3.0            1.4           0.2  Iris-setosa   
2            4.7           3.2            1.3           0.2  Iris-setosa   
3            4.6           3.1            1.5           0.2  Iris-setosa   
4            5.0           3.6            1.4           0.2  Iris-setosa   

   SepalArea  
0      17.85  
1      14.70  
2      15.04  
3      14.26  
4      18.00  


#Dropping few rows

In [ ]:
df = df.drop(index=[0, 1, 2])

print("\nAfter dropping rows 0, 1, 2:\n")
print(df.head())



After dropping rows 0, 1, 2:

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
3            4.6           3.1            1.5           0.2  Iris-setosa   
4            5.0           3.6            1.4           0.2  Iris-setosa   
5            5.4           3.9            1.7           0.4  Iris-setosa   
6            4.6           3.4            1.4           0.3  Iris-setosa   
7            5.0           3.4            1.5           0.2  Iris-setosa   

   SepalArea  
3      14.26  
4      18.00  
5      21.06  
6      15.64  
7      17.00  


# Analysis Report

## Dataset Overview

In [ ]:
print("Dataset Shape:", df.shape)
print("\nMissing values per column:\n", df.isnull().sum())
print("\nDataset Info:")
df.info()

Dataset Shape: (147, 6)

Missing values per column:
 SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
SepalArea        0
dtype: int64

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 3 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  147 non-null    float64
 1   SepalWidthCm   147 non-null    float64
 2   PetalLengthCm  147 non-null    float64
 3   PetalWidthCm   147 non-null    float64
 4   Species        147 non-null    object 
 5   SepalArea      147 non-null    float64
dtypes: float64(5), object(1)
memory usage: 7.0+ KB


## Descriptive Statistics

In [ ]:
print("Descriptive Statistics:\n")
print(df.describe())

Descriptive Statistics:

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm   SepalArea
count     147.000000    147.000000     147.000000    147.000000  147.000000
mean        5.862585      3.050340       3.807483      1.219048   17.846190
std         0.824971      0.436263       1.748467      0.757278    3.385432
min         4.300000      2.000000       1.000000      0.100000   10.000000
25%         5.100000      2.800000       1.600000      0.300000   15.660000
50%         5.800000      3.000000       4.400000      1.300000   17.680000
75%         6.400000      3.300000       5.100000      1.800000   20.400000
max         7.900000      4.400000       6.900000      2.500000   30.020000


In [ ]:
print("Insights:")
print(f"\nThe average Sepal Length is: {df['SepalLengthCm'].mean():.2f}")
print(f"The median Sepal Width is: {df['SepalWidthCm'].median():.2f}")
print(f"The most common Species is: {df['Species'].mode()[0]}")

Insights:

The average Sepal Length is: 5.86
The median Sepal Width is: 3.00
The most common Species is: Iris-versicolor
